<meta name="robots" content="noindex,nofollow">
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Harmony's Cybersecurity Projects
description: Proof of skills for prospective employers
